name: Metrics - Análisis Profundo de Lenguajes
on:
  # Se ejecuta automáticamente todos los días a las 00:00 UTC (9 PM en Argentina)
  schedule: [{cron: "0 0 * * *"}]
  # Permite que ejecutes el script manualmente desde la pestaña "Actions" cuando quieras probarlo
  workflow_dispatch:
  # Se ejecuta de forma inmediata si realizás algún cambio en las ramas principales
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generar Tarjeta de Lenguajes In-Depth
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          template: classic
          base: ""
          config_padding: 0%
          
          # LENGUAJES
          plugin_languages: yes
          plugin_languages_indepth: yes 
          plugin_languages_limit: 10
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          
          # ESTÉTICA
          extras_css: |
            /* 1. Oculta el encabezado superior ("14 Languages") */
            .h2 { display: none !important; }
            
            /* 2. Pone en mayúscula la primera letra de cada palabra ("Most Used Languages") */
            .h3 { text-transform: capitalize !important; }
            
            /* 3. Cambia el color de ese subtítulo (reemplazá el HEX o borrá la línea si querés el original) */
            :root { --color-header: #238193 !important; }